name: glpi-evolution-zabbix

include:
  - Chatwoot/compose.yaml
  - GLPI/glpi.yml
  - Zabbix/zabbix.yml
  - evolution/compose.yaml
  - minio/compose.yaml
  - n8n/compose.yaml

networks:
  itsm_shared_net:
    external: true
  app_network:
    external: true
